Shipping Services Example Application
==========================

How to use Spring Boot, Spring Data, and Neo4j together.

Spring Data Neo4j enables convenient integration of Neo4j in your Spring-based application.
It provides object-graph mapping (OGM) functionality and other features common to the Spring Data projects.

[NOTE]
*This project uses Spring Data Neo4j 5.*
It is optimized for working with Neo4j Desktop and based on Neo4j's query language

== Quickstart

. http://neo4j.com/download[Download, install, and start Neo4j Desktop].
. From here, there are two ways you can access the end points.
    1) Open the browser web interface at http://localhost:8080
        a. Configure a username and password, if you haven't already.
    2) In Neo4j Desktop, click on your project, click on 'Manage' on the database you are using, click 'Open Browser'.
        a. Should not need to log in. Password was set up when you set up the database.
. Clone this project from GitHub
. Update `src/main/resources/application.properties` with the username and password you set above.
. Run the project with `mvn spring-boot:run`.

== Code Walkthrough
There are Person, Order, Address repositories and their respecting POJO to handle the data and couple of APIS GET /savegraph(Testing purpose will create some entries for you) and

APIs Exposed:
1.POST /saveGraphPost which takes in object OrderRequest java object and saves it if there is no existing orderNumber otherwise throws exception
Post Body:

{
  "orderNumber":1,
  "orderType":"SampleOrderType",
  "sourceAddress":{
  	"zip":12345,
  	"street":"Sample Street",
  	"city":"City",
  	"house":2
  },
   "destinationAddress":{
  	"zip":12346,
  	"street":"Sample Street",
  	"city":"City",
  	"house":4
  },
  "personName":"Name",
  "personBorn":2019
}

2. /getOrders: Gets you the orders created

.pom.xml
[source,xml]
----
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-neo4j</artifactId>
</dependency>
----
include::pom.xml[tags=dependencies]

Annotate your `@NodeEntity` and `@RelationshipEntity`. You can use the OGM `Session` to access Neo4j APIs and object graph mapping functionality.



== The Stack

These are the components of our Web Application:

* Application Type:         Spring-Boot Java Web Application (Jetty)
* Web framework:            Spring-Boot enabled Spring-WebMVC, Spring-Data-Rest
* Persistence Access:       Spring-Data-Neo4j 5.0.5
* Database:                 Neo4j-Server 3.3.x

curl http://localhost:8080/graph
----
